import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/theme-provider"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen">
            <SidebarWrapper />
            <div className="flex-1 flex flex-col md:pl-64 transition-all duration-300">
              <HeaderWrapper />
              <main className="flex-1 p-6 bg-slate-50/50 dark:bg-slate-950/50">
                {children}
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

import { Sidebar } from "@/components/layout/sidebar";
import { Header } from "@/components/layout/header";

function SidebarWrapper() {
  return <Sidebar className="hidden md:block w-64 fixed h-full z-30" />;
}

function HeaderWrapper() {
  return <Header />;
}
